
    
language: python
dist: xenial   # required for Python >= 3.7
python:
  - "3.7"

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin/
  - export CHROME_BIN=chromium-browser

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r requirements.txt

script:
  - python --version
  - behave