
    
language: python
sudo: false
dist: xenial   # required for Python >= 3.7
python:
  - "3.7"
  - "2.7"

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser

env:
  global:
    - RUN_HEADLESS=TRUE

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r requirements.txt

script:
  - python --version
  - behave

after_failure:
  - echo "FAILURE DETAILS (from XML reports):"
  - bin/behave.junit_filter.py --status=failed reports